import "./globals.css";

import { Layout } from "@shared/ui/next";
import type { Metadata } from "next";
import { Nanum_Gothic, Nanum_Gothic_Coding } from "next/font/google";

import AuthButton from "@/components/auth-button";
import Provider from "@/components/provider";

const nanumGothic = Nanum_Gothic({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-nanum-sans",
});

const nanumGothicCoding = Nanum_Gothic_Coding({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-nanum-mono",
});

export const metadata: Metadata = {
  title: "Auth.js Example",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <Provider>
        <Layout
          title="Auth.js Example"
          links={[{ name: "Show DB", href: "/db" }]}
          right={<AuthButton />}
          sansVariable={nanumGothic.variable}
          monoVariable={nanumGothicCoding.variable}
        >
          {children}
        </Layout>
      </Provider>
    </html>
  );
}
