import type { Metadata } from "next";
import { Nanum_Gothic, Nanum_Gothic_Coding } from "next/font/google";
import "./globals.css";
import { Layout } from "@shared/ui/next";

const nanumGothic = Nanum_Gothic({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-nanum-sans",
});

const nanumGothicCoding = Nanum_Gothic_Coding({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-nanum-mono",
});

export const metadata: Metadata = {
  title: "Add Topic Name",
  description: "Generated by @shared/create-topic",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <Layout
        title="Add Topic Name"
        sansVariable={nanumGothic.variable}
        monoVariable={nanumGothicCoding.variable}
      >
        {children}
      </Layout>
    </html>
  );
}
