import type { Metadata } from "next";
import { Nanum_Gothic, Nanum_Gothic_Coding } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/navbar";
import Provider from "@/components/provider";

const nanumGothic = Nanum_Gothic({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-nanum-sans",
});

const nanumGothicCoding = Nanum_Gothic_Coding({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-nanum-mono",
});

export const metadata: Metadata = {
  title: "NextAuth.js Example",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        className={`${nanumGothic.variable} ${nanumGothicCoding.variable} antialiased`}
      >
        <div className="relative flex flex-col min-h-screen font-sans">
          <Provider>
            <NavBar />
            <main className="flex-1 flex flex-col p-8">{children}</main>
          </Provider>
        </div>
      </body>
    </html>
  );
}
