import "./globals.css";

import { Layout } from "@shared/ui/next";
import type { Metadata } from "next";
import { Nanum_Gothic, Nanum_Gothic_Coding } from "next/font/google";

import Providers from "@/components/providers";

const nanumGothic = Nanum_Gothic({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-nanum-sans",
});

const nanumGothicCoding = Nanum_Gothic_Coding({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-nanum-mono",
});

export const metadata: Metadata = {
  title: "React Query",
  description: "Generated by create-topic",
};

const links = [
  { name: "Server", href: "/server" },
  { name: "React Query", href: "/react-query" },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <Providers>
        <Layout
          title="react-query"
          sansVariable={nanumGothic.variable}
          monoVariable={nanumGothicCoding.variable}
          links={links}
        >
          {children}
        </Layout>
      </Providers>
    </html>
  );
}
