import "./globals.css";

import { Layout } from "@shared/ui/next";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import type { Metadata } from "next";
import { Nanum_Gothic, Nanum_Gothic_Coding } from "next/font/google";

import Providers from "@/components/providers";

const nanumGothic = Nanum_Gothic({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-nanum-sans",
});

const nanumGothicCoding = Nanum_Gothic_Coding({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-nanum-mono",
});

export const metadata: Metadata = {
  title: "React Query",
  description: "Generated by create-topic",
};

const links = [
  { name: "Experiment 1", href: "/experiment-1" },
  { name: "Experiment 2", href: "/experiment-2" },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <Providers>
        <Layout
          title="react-query"
          sansVariable={nanumGothic.variable}
          monoVariable={nanumGothicCoding.variable}
          links={links}
        >
          {children}
          <ReactQueryDevtools />
        </Layout>
      </Providers>
    </html>
  );
}
